apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-kotlin-spring
  labels:
    app: sample-kotlin-spring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: sample-kotlin-spring
  template:
    spec:
      containers:
        - name: sample-kotlin-spring
          resizePolicy:
            - resourceName: "cpu"
              restartPolicy: "NotRequired"
          resources:
            limits:
              cpu: '0.5'
            requests:
              cpu: '0.1'