apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: resize-pod-policy
spec:
  rules:
    - name: resize-pod-policy
      match:
        any:
          - resources:
              kinds:
                - v1/Pod.status
      preconditions:
        all:
          - key: "{{request.object.status.containerStatuses[0].ready}}"
            operator: Equals
            value: true
      mutate:
        targets:
          - apiVersion: v1
            kind: Pod
            name: '{{request.object.metadata.name}}'
            namespace: demo
        patchStrategicMerge:
          spec:
            containers:
              - (name): sample-kotlin-spring
                resources:
                  limits:
                    cpu: 0.5